---
title: "The Effect of Riparian Vegetation Density on the Nitrogen Content of Surface Water"
author: Davis Chase Dudley, Ricardo Monsalve, Jack D'Antonio
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
Chunk 1 ^^^


```{r import packages}

#In Chunk 2, we're loading in the packages necessary to manipulate and process our data for further analysis.

install.packages("dplyr")
install.packages("tidyr")
install.packages("ggplot2")
install.packages("readr")
install.packages("lubridate")

library(dplyr)
library(tidyr)
library(ggplot2)
library(readr)
library(lubridate)

```
Chunk 2 ^^^


```{r load data sets}

#In Chunk 3, we're loading all of the raw NEON data sets that we're going to be using in our project, so that they're immediately accessible and available within the .rmd. Additionally, we're tagging each with an appropriate siteID (derived from the NEON site wherein the data was collected) and a year (derived from the year within which the data was collected). 

# (Note: Each set of data is preceded by a textual title (example: #BIGC_2019) to facilitate any necessary navigation).


#BIGC_2019

Nitrate_BIGC_2019 <-read_csv("../Data/Processed/BIGC (CA-D17)/BIGC_NEON_nitrate-surfacewater/NEON.D17.BIGC.DP1.20033.001.102.100.015.NSW_15_minute.2019-07.basic.20221201T190523Z.csv") %>% 
  mutate(siteID="BIGC", year=2019)

VegCover_BIGC_2019 <- read_csv("../Data/Processed/BIGC (CA-D17)/BIGC_NEON_cover-veg-riparian/NEON.D17.BIGC.DP1.20191.001.rip_percentComposition.2019-07.basic.20230112T002213Z.csv") %>% 
  mutate(siteID="BIGC", year=2019)


#BIGC_2021

Nitrate_BIGC_2021 <-read_csv("../Data/Processed/BIGC (CA-D17)/BIGC_NEON_nitrate-surfacewater/NEON.D17.BIGC.DP1.20033.001.102.100.015.NSW_15_minute.2021-08.basic.20221201T175835Z.csv") %>% 
  mutate(siteID="BIGC", year=2021)

VegCover_BIGC_2021 <- read_csv("../Data/Processed/BIGC (CA-D17)/BIGC_NEON_cover-veg-riparian/NEON.D17.BIGC.DP1.20191.001.rip_percentComposition.2021-08.basic.20230112T001807Z.csv") %>% 
  mutate(siteID="BIGC", year=2021)


#BLUE_2019

Nitrate_BLUE_2019 <-read_csv("../Data/Processed/BLUE (OK-D11)/BLUE_NEON_nitrate-surfacewater/NEON.D11.BLUE.DP1.20033.001.112.100.015.NSW_15_minute.2019-06.basic.20221201T045009Z.csv") %>% 
  mutate(siteID="BLUE", year=2019)

VegCover_BLUE_2019 <-read_csv("../Data/Processed/BLUE (OK-D11)/BLUE_NEON_cover-veg-riparian/NEON.D11.BLUE.DP1.20191.001.rip_percentComposition.2019-06.basic.20230112T002006Z.csv") %>% 
  mutate(siteID="BLUE", year=2019)


#BLUE_2021

Nitrate_BLUE_2021 <-read_csv("../Data/Processed/BLUE (OK-D11)/BLUE_NEON_nitrate-surfacewater/NEON.D11.BLUE.DP1.20033.001.112.100.015.NSW_15_minute.2021-06.basic.20221201T013159Z.csv") %>% 
  mutate(siteID="BLUE", year=2021)

VegCover_BLUE_2021 <-read_csv("../Data/Processed/BLUE (OK-D11)/BLUE_NEON_cover-veg-riparian/NEON.D11.BLUE.DP1.20191.001.rip_percentComposition.2021-06.basic.20230112T002305Z.csv") %>% 
  mutate(siteID="BLUE", year=2021)


#LECO_2019

Nitrate_LECO_2019 <-read_csv("../Data/Processed/LECO (TN-D07)/LECO_NEON_nitrate-surfacewater/NEON.D07.LECO.DP1.20033.001.102.100.015.NSW_15_minute.2019-09.basic.20221208T002007Z.csv") %>% 
  mutate(siteID="LECO", year=2019)

VegCover_LECO_2019 <-read_csv("../Data/Processed/LECO (TN-D07)/LECO_NEON_cover-veg-riparian/NEON.D07.LECO.DP1.20191.001.rip_percentComposition.2019-09.basic.20230112T001930Z.csv") %>% 
  mutate(siteID="LECO", year=2019)


#LECO_2021

Nitrate_LECO_2021 <-read_csv("../Data/Processed/LECO (TN-D07)/LECO_NEON_nitrate-surfacewater/NEON.D07.LECO.DP1.20033.001.112.100.015.NSW_15_minute.2021-09.basic.20221208T012753Z.csv") %>% 
  mutate(siteID="LECO", year=2021)

VegCover_LECO_2021 <-read_csv("../Data/Processed/LECO (TN-D07)/LECO_NEON_cover-veg-riparian/NEON.D07.LECO.DP1.20191.001.rip_percentComposition.2021-09.basic.20230112T002003Z.csv") %>% 
  mutate(siteID="LECO", year=2021)


```
Chunk 3 ^^^


```{r Compile Data into Single Data Frame}

#In Chunk 4, all of the extraneous data from the raw data sheets is being excised, and the data pertaining to our project is being consolidated into multiple formats in order to facilitate further analysis and manipulation. These are detailed in pre-code titles below, but generally speaking, we are creating a data frame containing all of the 'surfWaterNitrateMean' data from the Nitrate_Surfacewater NEON data sheets and a separate frame containing all of the 'canopyCoverPercent' data from the Cover_Veg_Riparian NEON data sheets (these will be used in the creation of two single-variable histograms). We're then creating mean data for each of these consolidated data frames (grouped by siteID and year) before finally left_joining these mean data to create a summarized master data frame.


#Nitrate Data Consolidation (Total, then mean surfWaterNitrateMean grouped by SiteID and year)
Nitrate_Combined <- bind_rows(Nitrate_BIGC_2019, Nitrate_BIGC_2021, Nitrate_BLUE_2019, Nitrate_BLUE_2021, Nitrate_LECO_2019, Nitrate_LECO_2021)

Mean_Nitrate_Combined <- Nitrate_Combined %>% 
  drop_na() %>% 
  group_by(siteID, year) %>% 
  summarize(mean_conc_nitrate = mean(surfWaterNitrateMean))


#VegCover Data Consolidation (Total, then mean canopyCoverPercent grouped by SiteID and year)
VegCover_Combined <- bind_rows(VegCover_BIGC_2019, VegCover_BIGC_2021, VegCover_BLUE_2019, VegCover_BLUE_2021, VegCover_LECO_2019, VegCover_LECO_2021)

Mean_VegCover_Combined <- VegCover_Combined %>% 
  group_by(siteID, year) %>% 
  summarize(mean_veg_cover = mean(canopyCoverPercent))


#Summary Data Frame (with corresponding mean values)
Master_Data_Frame <- left_join(Mean_Nitrate_Combined, Mean_VegCover_Combined)



#Raw 'surfWaterNitrateMean' and 'canopyCoverPercent' columns for Histogram
Total_Nitrate_Conc_Combined <- Nitrate_Combined %>% 
  drop_na() %>% 
  select(surfWaterNitrateMean)

Total_VegCover_Combined <- VegCover_Combined %>% 
  select(canopyCoverPercent)


```
Chunk 4 ^^^


```{r Histogram}

# In Chunk 5, we're using the data frames containing the compiled 'surfWaterNitrateMean' and 'canopyCoverPercent' columns to create two single-variable histograms, each representative of one of our two continuous variables (both our response and our predictor variable). These histograms will give us a better understanding of the distribution of our variable values, which could help us to draw more accurate conclusions about the relationships we're observing down the line (as well as help us to explain any potential anomalies that arise).


Total_Nitrate_Conc_Combined %>%
  ggplot(aes(x=surfWaterNitrateMean))+
  geom_histogram()

Total_VegCover_Combined %>%
  ggplot(aes(x=canopyCoverPercent))+
  geom_histogram()


```
Chunk 5 ^^^


```{r Data Frame For Graphical Analysis}

#In Chunk 6, we are creating data frames containing the summarized data necessary for visualization and analysis, specifically to facilitate the creation of figures by making all of the pertinent data immediately available in a single data frame. (Note: Much of this code is the same as that contained in Chunk 4; for the purposes of our project, it made sense to summarize our data prior to compilation, and as such, much of it already exists in a grouped and summarized format).


#Nitrate Data Consolidation (Total, then mean surfWaterNitrateMean grouped by SiteID and year)
Nitrate_Combined <- bind_rows(Nitrate_BIGC_2019, Nitrate_BIGC_2021, Nitrate_BLUE_2019, Nitrate_BLUE_2021, Nitrate_LECO_2019, Nitrate_LECO_2021)

Mean_Nitrate_Combined <- Nitrate_Combined %>% 
  drop_na() %>% 
  group_by(siteID, year) %>% 
  summarize(mean_conc_nitrate = mean(surfWaterNitrateMean))


#VegCover Data Consolidation (Total, then mean canopyCoverPercent grouped by SiteID and year)
VegCover_Combined <- bind_rows(VegCover_BIGC_2019, VegCover_BIGC_2021, VegCover_BLUE_2019, VegCover_BLUE_2021, VegCover_LECO_2019, VegCover_LECO_2021)

Mean_VegCover_Combined <- VegCover_Combined %>% 
  group_by(siteID, year) %>% 
  summarize(mean_veg_cover = mean(canopyCoverPercent))


#Summary Data Frame (with corresponding mean values)
Master_Data_Frame <- left_join(Mean_Nitrate_Combined, Mean_VegCover_Combined)

```
Chunk 6 ^^^


```{r Rough Draft Graphs}

#Bar Graph
Master_Data_Frame %>%
  drop_na()%>%
  group_by(siteID, year)%>%
  ggplot(aes(x=mean_veg_cover, y=mean_conc_nitrate, fill = siteID))+
  geom_col(position="dodge")

#Scatter Plot
Master_Data_Frame %>%
  ggplot(aes(x=mean_veg_cover, y=mean_conc_nitrate))+
  geom_point()+
  geom_smooth(method ="lm")+
  theme_classic()


#ANOVA

ANOVA_Model <- aov(mean_conc_nitrate~mean_veg_cover, data = Master_Data_Frame)
summary(ANOVA_Model)

#Linear Model

Linear_Model <- lm(mean_conc_nitrate~mean_veg_cover, data = Master_Data_Frame)
summary(Linear_Model)
plot(Linear_Model)

```









Code Template Bank Below__________________________

Code Template:

{Insert Name} \<-read_csv("../Data/Processed/FILE_NAME_FOR_SITE/FILE_NAME_FOR_DATA_TYPE/EXCEL_SHEET_NAME.csv")

```{r Code Template}

Nitrate_BIGC_2019 <-read_csv("../Data/Processed/BIGC (CA-D17)/BIGC_NEON_nitrate-surfacewater/NEON.D17.BIGC.DP1.20033.001.102.100.015.NSW_15_minute.2019-07.basic.20221201T190523Z.csv")

VegCover_BIGC_2019 <- read_csv("../Data/Processed/BIGC (CA-D17)/BIGC_NEON_cover-veg-riparian/NEON.D17.BIGC.DP1.20191.001.rip_percentComposition.2019-07.basic.20230112T002213Z.csv")

CompStruct_BIGC_2019 <- read_csv("../Data/Processed/BIGC (CA-D17)/BIGC_NEON_comp-struct-riparian/NEON.D17.BIGC.DP1.20275.001.rip_assessment.2019-07.basic.20221128T182237Z.csv")

ChemSurf_BIGC_2019 <- read_csv("../Data/Processed/BIGC (CA-D17)/BIGC_NEON_chem-surfacewater/NEON.D17.BIGC.DP1.20093.001.swc_externalLabDataByAnalyte.2019-07.basic.20221215T171932Z.csv")

```

```{r data hub Nitrate and VegCover}

#BIGC_2019

Nitrate_BIGC_2019 <-read_csv("../Data/Processed/BIGC (CA-D17)/BIGC_NEON_nitrate-surfacewater/NEON.D17.BIGC.DP1.20033.001.102.100.015.NSW_15_minute.2019-07.basic.20221201T190523Z.csv")

VegCover_BIGC_2019 <- read_csv("../Data/Processed/BIGC (CA-D17)/BIGC_NEON_cover-veg-riparian/NEON.D17.BIGC.DP1.20191.001.rip_percentComposition.2019-07.basic.20230112T002213Z.csv")


#BIGC_2021

Nitrate_BIGC_2021 <-read_csv("../Data/Processed/BIGC (CA-D17)/BIGC_NEON_nitrate-surfacewater/NEON.D17.BIGC.DP1.20033.001.102.100.015.NSW_15_minute.2021-08.basic.20221201T175835Z.csv")

VegCover_BIGC_2021 <- read_csv("../Data/Processed/BIGC (CA-D17)/BIGC_NEON_cover-veg-riparian/NEON.D17.BIGC.DP1.20191.001.rip_percentComposition.2021-08.basic.20230112T001807Z.csv")


#BLUE_2019

Nitrate_BLUE_2019 <-read_csv("../Data/Processed/BLUE (OK-D11)/BLUE_NEON_nitrate-surfacewater/NEON.D11.BLUE.DP1.20033.001.112.100.015.NSW_15_minute.2019-06.basic.20221201T045009Z.csv")

VegCover_BLUE_2019 <-read_csv("../Data/Processed/BLUE (OK-D11)/BLUE_NEON_cover-veg-riparian/NEON.D11.BLUE.DP1.20191.001.rip_percentComposition.2019-06.basic.20230112T002006Z.csv")


#BLUE_2021

Nitrate_BLUE_2021 <-read_csv("../Data/Processed/BLUE (OK-D11)/BLUE_NEON_nitrate-surfacewater/NEON.D11.BLUE.DP1.20033.001.112.100.015.NSW_15_minute.2021-06.basic.20221201T013159Z.csv")

VegCover_BLUE_2021 <-read_csv("../Data/Processed/BLUE (OK-D11)/BLUE_NEON_cover-veg-riparian/NEON.D11.BLUE.DP1.20191.001.rip_percentComposition.2021-06.basic.20230112T002305Z.csv")


#LECO_2019

Nitrate_LECO_2019 <-read_csv("../Data/Processed/LECO (TN-D07)/LECO_NEON_nitrate-surfacewater/NEON.D07.LECO.DP1.20033.001.102.100.015.NSW_15_minute.2019-09.basic.20221208T002007Z.csv")

VegCover_LECO_2019 <-read_csv("../Data/Processed/LECO (TN-D07)/LECO_NEON_cover-veg-riparian/NEON.D07.LECO.DP1.20191.001.rip_percentComposition.2019-09.basic.20230112T001930Z.csv")


#LECO_2021

Nitrate_LECO_2021 <-read_csv("../Data/Processed/LECO (TN-D07)/LECO_NEON_nitrate-surfacewater/NEON.D07.LECO.DP1.20033.001.112.100.015.NSW_15_minute.2021-09.basic.20221208T012753Z.csv")

VegCover_LECO_2021 <-read_csv("../Data/Processed/LECO (TN-D07)/LECO_NEON_cover-veg-riparian/NEON.D07.LECO.DP1.20191.001.rip_percentComposition.2021-09.basic.20230112T002003Z.csv")


```

```{r mean data code format}

NBIGC2019Mean <- Nitrate_BIGC_2019 %>%
  drop_na(surfWaterNitrateMean) %>% 
  summarize(mean_conc_BIGC_2019 = mean(surfWaterNitrateMean))


Nitrate_BIGC_2021 %>%
  drop_na(surfWaterNitrateMean) %>% 
  summarize(mean_conc_BIGC_2021 = mean(surfWaterNitrateMean))


Nitrate_BLUE_2019 %>%
  drop_na(surfWaterNitrateMean) %>% 
  summarize(mean_conc_BLUE_2019 = mean(surfWaterNitrateMean))


Nitrate_BLUE_2021 %>%
  drop_na(surfWaterNitrateMean) %>% 
  summarize(mean_conc_BLUE_2021 = mean(surfWaterNitrateMean))


Nitrate_LECO_2019 %>%
  drop_na(surfWaterNitrateMean) %>% 
  summarize(mean_conc_LECO_2019 = mean(surfWaterNitrateMean))


Nitrate_LECO_2021 %>%
  drop_na(surfWaterNitrateMean) %>% 
  summarize(mean_conc_LECO_2021 = mean(surfWaterNitrateMean))


VegCover_BIGC_2019 %>%
  drop_na(canopyCoverPercent) %>% 
  summarize(mean_cover_perc_BIGC_2019 = mean(canopyCoverPercent))


VegCover_BIGC_2021 %>%
  drop_na(canopyCoverPercent) %>% 
  summarize(mean_cover_perc_BIGC_2021 = mean(canopyCoverPercent))


VegCover_BLUE_2019 %>%
  drop_na(canopyCoverPercent) %>% 
  summarize(mean_cover_perc_BLUE_2019 = mean(canopyCoverPercent))


VegCover_BLUE_2021 %>%
  drop_na(canopyCoverPercent) %>% 
  summarize(mean_cover_perc_BLUE_2021 = mean(canopyCoverPercent))


VegCover_LECO_2019 %>%
  drop_na(canopyCoverPercent) %>% 
  summarize(mean_cover_perc_LECO_2019 = mean(canopyCoverPercent))


VegCover_LECO_2021 %>%
  drop_na(canopyCoverPercent) %>% 
  summarize(mean_cover_perc_LECO_2021 = mean(canopyCoverPercent))


```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.

WORK IN PROGRESS BELOW

```{r}

Nitrate_BIGC_select_2019 <- Nitrate_BIGC_2019 %>% 
  select(surfWaterNitrateMean)

VegCover_BIGC_select_2019 <- VegCover_BIGC_2019 %>% 
  select(canopyCoverPercent)

Nitrate_BIGC_select_2021 <- Nitrate_BIGC_2021 %>% 
  select(surfWaterNitrateMean)

VegCover_BIGC_select_2021 <- VegCover_BIGC_2021 %>% 
  select(canopyCoverPercent)

Nitrate_BLUE_select_2019 <- Nitrate_BLUE_2019 %>% 
  select(surfWaterNitrateMean)

VegCover_BLUE_select_2019 <- VegCover_BLUE_2019 %>% 
  select(canopyCoverPercent)

Nitrate_BLUE_select_2021 <- Nitrate_BLUE_2021 %>% 
  select(surfWaterNitrateMean)

VegCover_BLUE_select_2021 <- VegCover_BLUE_2021 %>% 
  select(canopyCoverPercent)

Nitrate_LECO_select_2019 <- Nitrate_LECO_2019 %>% 
  select(surfWaterNitrateMean)

VegCover_LECO_select_2019 <- VegCover_LECO_2019 %>% 
  select(canopyCoverPercent)

Nitrate_LECO_select_2021 <- Nitrate_LECO_2021 %>% 
  select(surfWaterNitrateMean)

VegCover_LECO_select_2021 <- VegCover_LECO_2021 %>% 
  select(canopyCoverPercent)


Total_VegCover_Combined <- bind_cols(VegCover_BIGC_select_2019, VegCover_BIGC_select_2021, VegCover_BLUE_select_2019, VegCover_BLUE_select_2021, VegCover_LECO_select_2019, VegCover_LECO_select_2021)

Total_VegCover_Combined_One_Col <- bind_rows(VegCover_BIGC_select_2019, VegCover_BIGC_select_2021, VegCover_BLUE_select_2019, VegCover_BLUE_select_2021, VegCover_LECO_select_2019, VegCover_LECO_select_2021)

Total_Nitrate_Combined_One_Col <- bind_rows(Nitrate_BIGC_select_2019, Nitrate_BIGC_select_2021, Nitrate_BLUE_select_2019, Nitrate_BLUE_select_2021, Nitrate_LECO_select_2019, Nitrate_LECO_select_2021)

Master_Sheet_Total <- left_join(x = Total_VegCover_Combined_One_Col, y = Total_Nitrate_Combined_One_Col)

```

Scraps\_\_\_\_\_\_\_\_\_\_\_\_

```{r mean data code format}

NBIGC2019Mean <- Nitrate_BIGC_2019 %>%
  drop_na(surfWaterNitrateMean) %>% 
  summarize(mean_conc_BIGC_2019 = mean(surfWaterNitrateMean))


NBIGC2021Mean <- Nitrate_BIGC_2021 %>%
  drop_na(surfWaterNitrateMean) %>% 
  summarize(mean_conc_BIGC_2021 = mean(surfWaterNitrateMean))


NBLUE2019Mean <- Nitrate_BLUE_2019 %>%
  drop_na(surfWaterNitrateMean) %>% 
  summarize(mean_conc_BLUE_2019 = mean(surfWaterNitrateMean))


NBLUE2021Mean <- Nitrate_BLUE_2021 %>%
  drop_na(surfWaterNitrateMean) %>% 
  summarize(mean_conc_BLUE_2021 = mean(surfWaterNitrateMean))


NLECO2019Mean <- Nitrate_LECO_2019 %>%
  drop_na(surfWaterNitrateMean) %>% 
  summarize(mean_conc_LECO_2019 = mean(surfWaterNitrateMean))


NLECO2021Mean <- Nitrate_LECO_2021 %>%
  drop_na(surfWaterNitrateMean) %>% 
  summarize(mean_conc_LECO_2021 = mean(surfWaterNitrateMean))


VBIGC2019Mean <- VegCover_BIGC_2019 %>%
  drop_na(canopyCoverPercent) %>% 
  summarize(mean_cover_perc_BIGC_2019 = mean(canopyCoverPercent))


VBIGC2021Mean <- VegCover_BIGC_2021 %>%
  drop_na(canopyCoverPercent) %>% 
  summarize(mean_cover_perc_BIGC_2021 = mean(canopyCoverPercent))


VBLUE2019Mean <- VegCover_BLUE_2019 %>%
  drop_na(canopyCoverPercent) %>% 
  summarize(mean_cover_perc_BLUE_2019 = mean(canopyCoverPercent))


VBLUE2021Mean <- VegCover_BLUE_2021 %>%
  drop_na(canopyCoverPercent) %>% 
  summarize(mean_cover_perc_BLUE_2021 = mean(canopyCoverPercent))


VLECO2019Mean <- VegCover_LECO_2019 %>%
  drop_na(canopyCoverPercent) %>% 
  summarize(mean_cover_perc_LECO_2019 = mean(canopyCoverPercent))


VLECO2021Mean <- VegCover_LECO_2021 %>%
  drop_na(canopyCoverPercent) %>% 
  summarize(mean_cover_perc_LECO_2021 = mean(canopyCoverPercent))



Mean_Nitrate_Combined <- bind_rows(NBIGC2019Mean, NBIGC2021Mean, NBLUE2019Mean, NBLUE2021Mean, NLECO2019Mean, NLECO2021Mean)

Mean_VegCover_Combined <- bind_rows(VBIGC2019Mean, VBIGC2021Mean, VBLUE2019Mean, VBLUE2021Mean, VLECO2019Mean, VLECO2021Mean)

Master_Data_Frame <- bind_cols(Mean_Nitrate_Combined, Mean_VegCover_Combined)


```
